"""
Sensor Lab 전용 설정 (sim2sim_test 무의존)
"""

# 카메라
SENSOR_LAB_CAMERA_EYE = [0.65, -0.57279, 1.02]
SENSOR_LAB_CAMERA_TARGET = [1.0, 10, 1.0]
SENSOR_LAB_CAMERA_PRIM_PATH = "/OmniverseKit_Persp"

# World/LoadButton
PHYSICS_DT = 1 / 50.0
RENDERING_DT = 1 / 50.0
GRAVITY = [0, 0, -9.81]
WORLD_CONTROLS_COLLAPSED = True

# UI 레이아웃·색상 (World Controls 빌더용)
SPACING_SMALL = 5
SPACING_MEDIUM = 8
SIDEBAR_WIDTH = 4
BUTTON_HEIGHT = 30
BUTTON_BORDER_RADIUS = 2
SIDEBAR_SUCCESS = 0xFF2ECC40
SIDEBAR_RESET = 0xFF2E2ECC
LOAD_BUTTON_BG = 0xFF0D4F1C
LOAD_BUTTON_BORDER = 0xFF2ECC40
LOAD_BUTTON_HOVER = 0xFF1A6B2A
RED_BUTTON_BG = 0xFF0D0D4F
RED_BUTTON_BORDER = 0xFF2E2ECC
RED_BUTTON_HOVER = 0xFF1A1A6B
STATE_BUTTON_BG = 0xFF0D4F1C
STATE_BUTTON_BORDER = 0xFF2ECC40
STATE_BUTTON_HOVER = 0xFF1A6B2A
TEXT_PRIMARY = 0xFFFFFFFF
BUTTON_BORDER_WIDTH_THICK = 2
BUTTON_BORDER_RADIUS_XLARGE = 4
BUTTON_MARGIN = 0
BUTTON_PADDING = 5
